"""Provider-neutral contracts for local subscription-backed LLM calls."""

from .types import (
    AuthMode,
    BackendCapabilities,
    CompletionRequest,
    CompletionResult,
    qualify_subscription_model,
    resolve_subscription_model,
    subscription_default_model,
    subscription_model_prefix,
    subscription_provider_for_model,
    validate_subscription_models,
    SubscriptionAuthError,
    SubscriptionBackend,
    SubscriptionLifecycleBackend,
    SubscriptionCredential,
    SubscriptionError,
    SubscriptionPolicyError,
    SubscriptionProvider,
    SubscriptionModel,
    SubscriptionRuntime,
    SubscriptionLoginTransaction,
    SubscriptionRuntimeRouter,
    SubscriptionStatus,
    SubscriptionTokenExpired,
    SubscriptionTransportError,
    SubscriptionUnsupportedRequest,
)

__all__ = [
    "AuthMode",
    "BackendCapabilities",
    "CompletionRequest",
    "CompletionResult",
    "qualify_subscription_model",
    "resolve_subscription_model",
    "subscription_default_model",
    "subscription_model_prefix",
    "subscription_provider_for_model",
    "validate_subscription_models",
    "SubscriptionAuthError",
    "SubscriptionBackend",
    "SubscriptionLifecycleBackend",
    "SubscriptionCredential",
    "SubscriptionError",
    "SubscriptionPolicyError",
    "SubscriptionProvider",
    "SubscriptionModel",
    "SubscriptionRuntime",
    "SubscriptionLoginTransaction",
    "SubscriptionRuntimeRouter",
    "SubscriptionStatus",
    "SubscriptionTokenExpired",
    "SubscriptionTransportError",
    "SubscriptionUnsupportedRequest",
]
