#!/usr/bin/env Rscript
#
# Build the per-dictionary corpus statistics LaTeX table (TSV rows/columns, gold graphemes, markup tag counts, MDF tag counts).
#
# Usage:
#   Rscript evaluations/scripts/dictionary_stats_table.R
#
# Output:
#   evaluations/tables/dictionary_stats.tex

suppressWarnings(suppressMessages({
  script_path <- commandArgs(trailingOnly = FALSE)
  script_arg <- sub("^--file=", "", script_path[grep("^--file=", script_path)])
  repo_root <- if (length(script_arg)) normalizePath(file.path(dirname(script_arg), "..", "..")) else getwd()
}))

stats_csv <- file.path(repo_root, "evaluations", "statistics", "dictionary_statistics_summary.csv")
output_dir <- file.path(repo_root, "tables", "tables")
output_path <- file.path(output_dir, "dictionary_stats.tex")

if (!file.exists(stats_csv)) {
  stop(sprintf("Dictionary statistics CSV not found: %s", stats_csv))
}

results <- read.csv(stats_csv, stringsAsFactors = FALSE)

# Coptic-English-Greek has pages on disk but no Stage 1 gold data and isn't
# part of the final dataset -- exclude it (all its stat columns are empty).
results <- results[results$language != "Coptic-English-Greek", ]

required_cols <- c(
  "language", "rows", "columns",
  "gold_grapheme_count", "bold_tag_count", "italic_tag_count", "tags"
)
missing_cols <- setdiff(required_cols, names(results))
if (length(missing_cols)) {
  stop(sprintf("Missing expected column(s) in dictionary statistics CSV: %s", paste(missing_cols, collapse = ", ")))
}

results <- results[order(results$language), ]

fmt_int <- function(x) format(x, big.mark = ",", scientific = FALSE, trim = TRUE)
fmt_optional <- function(x) ifelse(is.na(x) | x == "", "--", fmt_int(as.integer(x)))

display_dictionary_name <- function(x) sub("Kurdish_Turkish", "Kurdish-Turkish", x, fixed = TRUE)

data_lines <- sprintf(
  "%s & %s & %s & %s & %s & %s & %s \\\\",
  display_dictionary_name(results$language),
  fmt_int(results$rows),
  fmt_int(results$columns),
  fmt_int(results$gold_grapheme_count),
  fmt_int(results$bold_tag_count),
  fmt_int(results$italic_tag_count),
  fmt_optional(results$tags)
)

lines <- c(
  "% Auto-generated by evaluations/scripts/dictionary_stats_table.R -- do not edit by hand.",
  "\\begin{table*}[t]",
  "\\centering",
  "\\scriptsize",
  "\\caption{Per-dictionary corpus statistics. Rows/Columns describe the Stage 1 gold TSV; Graphemes is the gold grapheme count; Bold/Italic are Stage 1 markup tag counts; MDF Tags counts \\textbackslash marker field lines in the Stage 2 gold MDF file (\\textrm{--} for dictionaries without Stage 2 gold data).}",
  "\\label{tab:dictionary-stats}",
  "\\begin{adjustbox}{max width=\\textwidth}",
  "\\begin{tabular}{lrrrrrr}",
  "\\toprule",
  "\\textbf{Dictionary} & \\textbf{Rows} & \\textbf{Columns} & \\textbf{Graphemes} & \\textbf{Bold} & \\textbf{Italic} & \\textbf{MDF Tags} \\\\",
  "\\midrule",
  data_lines,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{adjustbox}",
  "\\end{table*}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_path)

cat(sprintf("Wrote %s (%d dictionaries)\n", output_path, nrow(results)))
