#!/usr/bin/env python3
"""Generate the per-dictionary corpus-statistics LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from table_utils import (
    TableDataError,
    lines_to_text,
    parse_paths,
    read_delimited,
    write_text_atomic,
)

REQUIRED_COLUMNS = (
    "language",
    "rows",
    "columns",
    "gold_grapheme_count",
    "bold_tag_count",
    "italic_tag_count",
    "tags",
)


def _format_integer(value: str, *, source: Path, field: str, language: str) -> str:
    if value == "":
        raise TableDataError(f"{source}: {language}: {field} is blank")
    try:
        return f"{int(value):,}"
    except ValueError as exc:
        raise TableDataError(
            f"{source}: {language}: {field} must be an integer, got {value!r}"
        ) from exc


def render_table(repo_root: Path) -> str:
    """Render the dictionary-statistics table from its canonical CSV."""
    source = repo_root / "evaluations" / "statistics" / "dictionary_statistics_summary.csv"
    rows = read_delimited(source, required_columns=REQUIRED_COLUMNS)
    rows = sorted(
        (row for row in rows if row["language"] != "Coptic-English-Greek"),
        key=lambda row: row["language"],
    )

    data_lines: list[str] = []
    for row in rows:
        language = row["language"].replace("Kurdish_Turkish", "Kurdish-Turkish")
        values = [
            _format_integer(row[field], source=source, field=field, language=language)
            for field in REQUIRED_COLUMNS[1:-1]
        ]
        tags = (
            "--"
            if row["tags"] == ""
            else _format_integer(
                row["tags"], source=source, field="tags", language=language
            )
        )
        data_lines.append(f"{language} & {' & '.join([*values, tags])} \\\\")

    lines = [
        "% Auto-generated by tables/scripts/dictionary_stats_table.py -- do not edit by hand.",
        r"\begin{table*}[t]",
        r"\centering",
        r"\scriptsize",
        r"\caption{Per-dictionary corpus statistics. Rows/Columns describe the Stage 1 gold TSV; Graphemes is the gold grapheme count; Bold/Italic are Stage 1 markup tag counts; MDF Tags counts \textbackslash marker field lines in the Stage 2 gold MDF file (\textrm{--} for dictionaries without Stage 2 gold data).}",
        r"\label{tab:dictionary-stats}",
        r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        "\\textbf{Dictionary} & \\textbf{Rows} & \\textbf{Columns} & \\textbf{Graphemes} & \\textbf{Bold} & \\textbf{Italic} & \\textbf{MDF Tags} \\\\",
        r"\midrule",
        *data_lines,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{adjustbox}",
        r"\end{table*}",
    ]
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``dictionary_stats.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "dictionary_stats.tex"
    content = render_table(repo_root)
    write_text_atomic(output_path, content)
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
