#!/usr/bin/env python3
"""Generate the Stage 1 aggregate OCR evaluation LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from table_utils import (
    lines_to_text,
    parse_paths,
    read_stage1_aggregate,
    write_text_atomic,
)

METRICS = ("TextEdit", "GCER", "WER", "typography_f1", "ReadOrderEdit")
HIGHER_IS_BETTER = {metric: metric == "typography_f1" for metric in METRICS}
ROW_SPEC = (
    ("GLM-OCR-flat_noalpha", "GLM-OCR", False, "OCR systems"),
    ("GLM-OCR-flat_alpha", "GLM-OCR", True, "OCR systems"),
    ("Mathpix-OCR", "Mathpix", False, "OCR systems"),
    ("MinerU2.5-Pro", "MinerU2.5-Pro", False, "OCR systems"),
    ("PaddleOCR-VL-1.5", "PaddleOCR-VL-1.5", False, "OCR systems"),
    ("qwen3vl235_flat_noalpha", "Qwen3-VL-235B", False, "Vision Language Models"),
    ("qwen3vl235_flat_alpha", "Qwen3-VL-235B", True, "Vision Language Models"),
    ("claudeopus47_flat_noalpha", "Claude Opus 4.7", False, "General-purpose LLMs"),
    ("claudeopus47_flat_alpha", "Claude Opus 4.7", True, "General-purpose LLMs"),
    ("gpt55_flat_noalpha", "GPT-5.5", False, "General-purpose LLMs"),
    ("gpt55_flat_alpha", "GPT-5.5", True, "General-purpose LLMs"),
    ("gemini3flash_flat_noalpha", "Gemini 3 Flash", False, "General-purpose LLMs"),
    ("gemini3flash_flat_alpha", "Gemini 3 Flash", True, "General-purpose LLMs"),
    ("gemini31pro_flat_noalpha", "Gemini 3.1 Pro", False, "General-purpose LLMs"),
    ("gemini31pro_flat_alpha", "Gemini 3.1 Pro", True, "General-purpose LLMs"),
)


def _aggregate(evaluation_root: Path) -> list[dict[str, object]]:
    aggregates: list[dict[str, object]] = []
    for experiment, model, alphabet, section in ROW_SPEC:
        report = evaluation_root / experiment / "stage1_flat_evaluation_report.json"
        aggregates.append(
            {
                "experiment": experiment,
                "model": model,
                "alphabet": alphabet,
                "section": section,
                **read_stage1_aggregate(report),
            }
        )
    return aggregates


def render_table(repo_root: Path) -> str:
    """Render the Stage 1 aggregate table."""
    evaluation_root = repo_root / "evaluations" / "stage1_flat_per_lang_script_eval"
    rows = _aggregate(evaluation_root)
    best = {
        metric: (
            max(float(row[metric]) for row in rows)
            if HIGHER_IS_BETTER[metric]
            else min(float(row[metric]) for row in rows)
        )
        for metric in METRICS
    }

    def cell(metric: str, row: dict[str, object]) -> str:
        raw = float(row[metric])
        rendered = f"{raw:.2f}"
        return rf"\textbf{{{rendered}}}" if raw == best[metric] else rendered

    lines = [
        "% Auto-generated by tables/scripts/stage1_summary_table.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{1.6pt}",
        r"\renewcommand{\arraystretch}{1.00}",
        r"\caption{Stage 1 OCR evaluation results aggregated across 30 dictionaries, comparing transcription with and without the source-language alphabet list in the prompt. Check marks indicate that the alphabet (A) was supplied. \textit{Best aggregate scores are bolded: lower is better for Edit, GCER, WER, and Order; higher is better for Markup F1.}}",
        r"\label{tab:stage1-aggregate-alphabet}",
        r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tabular}{lcrrrrr}",
        r"\toprule",
        "\\textbf{Model} & \\textbf{A} & \\textbf{Edit} & \\textbf{GCER} & \\textbf{WER} & \\textbf{Mrk. F1} & \\textbf{Order} \\\\",
        r"\midrule",
    ]
    current_section: str | None = None
    for row in rows:
        section = str(row["section"])
        if section != current_section:
            if current_section is not None:
                lines.append(r"\midrule")
            lines.append(
                rf"\multicolumn{{7}}{{l}}{{\cellcolor{{gray!10}}\textit{{{section}}}}} \\"
            )
            current_section = section
        mark = r"\cmark" if row["alphabet"] else ""
        lines.append(
            f"{row['model']} & {mark} & {cell('TextEdit', row)} & {cell('GCER', row)} & "
            f"{cell('WER', row)} & {cell('typography_f1', row)} & {cell('ReadOrderEdit', row)} \\\\"
        )
    lines.extend((r"\bottomrule", r"\end{tabular}", r"\end{adjustbox}", r"\end{table}"))
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``stage1_summary.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "stage1_summary.tex"
    write_text_atomic(output_path, render_table(repo_root))
    print(
        f"Wrote {output_path} ({len(ROW_SPEC)} rows, aggregated over 30 dictionaries each)"
    )


if __name__ == "__main__":
    main()
