#!/usr/bin/env python3
"""Generate the Stage 2 typography-ablation LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from table_utils import TableDataError, lines_to_text, parse_float, parse_paths, read_delimited, write_text_atomic

METRICS = ("Record_Accuracy", "MDF_Fields_F1", "ReadOrderEdit")
HIGHER_IS_BETTER = {"Record_Accuracy": True, "MDF_Fields_F1": True, "ReadOrderEdit": False}
MODEL_ORDER = ("claudeopus47", "gemini31pro", "gpt55")
MODEL_DISPLAY = {
    "claudeopus47": "Claude Opus 4.7",
    "gemini31pro": "Gemini 3.1 Pro",
    "gpt55": "GPT-5.5",
}


def _one_row(rows: list[dict[str, str]], predicate: object, *, source: Path, description: str) -> tuple[int, dict[str, str]]:
    matched = [
        (row_number, row)
        for row_number, row in enumerate(rows, start=2)
        if predicate(row)  # type: ignore[operator]
    ]
    if len(matched) != 1:
        raise TableDataError(f"{source}: expected exactly one {description} row, found {len(matched)}")
    return matched[0]


def _pair(with_value: float, without_value: float, higher_is_better: bool) -> tuple[str, str]:
    formatted = (f"{with_value:.2f}", f"{without_value:.2f}")
    if with_value == without_value:
        return formatted
    with_wins = with_value > without_value if higher_is_better else with_value < without_value
    return (
        rf"\textbf{{{formatted[0]}}}" if with_wins else formatted[0],
        rf"\textbf{{{formatted[1]}}}" if not with_wins else formatted[1],
    )


def render_table(repo_root: Path) -> str:
    """Render the typography-ablation table."""
    baseline_source = repo_root / "evaluations" / "stage2_mdf_lang_script_eval_stage1-gold" / "stage2_mdf_eval_summary.csv"
    no_typography_root = repo_root / "evaluations" / "stage2_mdf_eval_no_typography"
    baseline_rows = read_delimited(
        baseline_source,
        required_columns=("experiment", "language", *METRICS),
    )
    data_lines: list[str] = []
    for model_key in MODEL_ORDER:
        experiment = f"{model_key}_high_mdf_intro_toolbox"
        baseline_number, baseline = _one_row(
            baseline_rows,
            lambda row, experiment=experiment: row["experiment"] == experiment and row["language"] == "__aggregate__",
            source=baseline_source,
            description=f"oracle aggregate for {experiment}",
        )
        no_typography_source = no_typography_root / model_key / "stage2_mdf_eval_summary.csv"
        no_typography_rows = read_delimited(
            no_typography_source,
            required_columns=("language", *METRICS),
        )
        no_typography_number, no_typography = _one_row(
            no_typography_rows,
            lambda row: row["language"] == "__aggregate__",
            source=no_typography_source,
            description="no-typography aggregate",
        )
        cells: list[str] = []
        for metric in METRICS:
            with_value = parse_float(
                baseline[metric], source=baseline_source, field=metric, row_number=baseline_number
            )
            without_value = parse_float(
                no_typography[metric], source=no_typography_source, field=metric, row_number=no_typography_number
            )
            cells.extend(_pair(with_value, without_value, HIGHER_IS_BETTER[metric]))
        data_lines.append(
            f"{MODEL_DISPLAY[model_key]} & \\cmark & \\cmark & {' & '.join(cells)} \\\\"
        )

    lines = [
        "% Auto-generated by tables/scripts/stage2_no_typography_table.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{3pt}",
        r"\caption{Stage 2 MDF evaluation results with vs.\ without typography (bold/italic markup) in the gold Stage 2 input, intro+MDF-toolbox condition. Baseline (with typography) values are the oracle-condition aggregate from Table~\ref{tab:stage2-mdf-aggregate}. \textit{Best score per pair is bolded; higher is better for Ent. Acc.\ and MDF F1, lower is better for ROE.}}",
        r"\label{tab:stage2-no-typography}",
        r"\begin{tabular}{lcccccccc}",
        r"\toprule",
        " & & & \\multicolumn{2}{c}{\\textbf{Ent. Acc.}} & \\multicolumn{2}{c}{\\textbf{MDF F1}} & \\multicolumn{2}{c}{\\textbf{ROE}} \\\\",
        r"\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}",
        "\\textbf{Model} & \\textbf{Intro} & \\textbf{MDF} & \\textbf{Tag} & \\textbf{No Tag} & \\textbf{Tag} & \\textbf{No Tag} & \\textbf{Tag} & \\textbf{No Tag} \\\\",
        r"\midrule",
        *data_lines,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``stage2_no_typography.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "stage2_no_typography.tex"
    write_text_atomic(output_path, render_table(repo_root))
    print(f"Wrote {output_path} ({len(MODEL_ORDER)} models)")


if __name__ == "__main__":
    main()
