#!/usr/bin/env Rscript
#
# Build the Stage 2 no-typography ablation LaTeX table, comparing MDF evaluation with vs. without bold/italic markup in the gold input.
#
# Usage:
#   Rscript evaluations/scripts/stage2_no_typography_table.R
#
# Output:
#   evaluations/tables/stage2_no_typography.tex

suppressWarnings(suppressMessages({
  script_path <- commandArgs(trailingOnly = FALSE)
  script_arg <- sub("^--file=", "", script_path[grep("^--file=", script_path)])
  repo_root <- if (length(script_arg)) normalizePath(file.path(dirname(script_arg), "..", "..")) else getwd()
}))

baseline_csv <- file.path(repo_root, "evaluations", "stage2_mdf_lang_script_eval_stage1-gold", "stage2_mdf_eval_summary.csv")
no_typo_root <- file.path(repo_root, "evaluations", "stage2_mdf_eval_no_typography")
output_dir <- file.path(repo_root, "tables", "tables")
output_path <- file.path(output_dir, "stage2_no_typography.tex")

if (!file.exists(baseline_csv)) {
  stop(sprintf("Oracle Stage 2 summary CSV not found: %s", baseline_csv))
}
if (!dir.exists(no_typo_root)) {
  stop(sprintf("No-typography evaluation folder not found: %s", no_typo_root))
}

metric_cols <- c("Record_Accuracy", "MDF_Fields_F1", "ReadOrderEdit")
higher_is_better <- c(Record_Accuracy = TRUE, MDF_Fields_F1 = TRUE, ReadOrderEdit = FALSE)

model_display <- c(
  claudeopus47 = "Claude Opus 4.7",
  gemini31pro = "Gemini 3.1 Pro",
  gpt55 = "GPT-5.5"
)
model_order <- c("claudeopus47", "gemini31pro", "gpt55")

baseline_results <- read.csv(baseline_csv, stringsAsFactors = FALSE)

fmt <- function(x) sprintf("%.2f", x)

# Bold whichever side of the pair is better, decided on full-precision values;
# exact ties left unbolded (same convention as the other Stage 2 tables).
pair_cells <- function(with_val, without_val, higher_better) {
  if (with_val == without_val) {
    return(c(fmt(with_val), fmt(without_val)))
  }
  with_wins <- if (higher_better) with_val > without_val else with_val < without_val
  c(
    if (with_wins) sprintf("\\textbf{%s}", fmt(with_val)) else fmt(with_val),
    if (!with_wins) sprintf("\\textbf{%s}", fmt(without_val)) else fmt(without_val)
  )
}

row_for_model <- function(model_key) {
  baseline_experiment <- sprintf("%s_high_mdf_intro_toolbox", model_key)
  baseline_row <- baseline_results[
    baseline_results$experiment == baseline_experiment & baseline_results$language == "__aggregate__",
  ]
  if (nrow(baseline_row) != 1) {
    stop(sprintf("Expected exactly one oracle aggregate row for %s, found %d.", baseline_experiment, nrow(baseline_row)))
  }

  no_typo_csv <- file.path(no_typo_root, model_key, "stage2_mdf_eval_summary.csv")
  if (!file.exists(no_typo_csv)) {
    stop(sprintf("No-typography summary CSV not found for %s: %s", model_key, no_typo_csv))
  }
  no_typo_results <- read.csv(no_typo_csv, stringsAsFactors = FALSE)
  no_typo_row <- no_typo_results[no_typo_results$language == "__aggregate__", ]
  if (nrow(no_typo_row) != 1) {
    stop(sprintf("Expected exactly one no-typography aggregate row for %s, found %d.", model_key, nrow(no_typo_row)))
  }

  cells <- unlist(lapply(metric_cols, function(col) {
    pair_cells(baseline_row[[col]], no_typo_row[[col]], higher_is_better[[col]])
  }))
  # This ablation only covers the intro+MDF-toolbox condition -- both flags
  # are enabled for every row.
  sprintf("%s & \\cmark & \\cmark & %s \\\\", model_display[[model_key]], paste(cells, collapse = " & "))
}

data_lines <- vapply(model_order, row_for_model, character(1))

lines <- c(
  "% Auto-generated by evaluations/scripts/stage2_no_typography_table.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\small",
  "\\setlength{\\tabcolsep}{3pt}",
  "\\caption{Stage 2 MDF evaluation results with vs.\\ without typography (bold/italic markup) in the gold Stage 2 input, intro+MDF-toolbox condition. Baseline (with typography) values are the oracle-condition aggregate from Table~\\ref{tab:stage2-mdf-aggregate}. \\textit{Best score per pair is bolded; higher is better for Ent. Acc.\\ and MDF F1, lower is better for ROE.}}",
  "\\label{tab:stage2-no-typography}",
  "\\begin{tabular}{lcccccccc}",
  "\\toprule",
  " & & & \\multicolumn{2}{c}{\\textbf{Ent. Acc.}} & \\multicolumn{2}{c}{\\textbf{MDF F1}} & \\multicolumn{2}{c}{\\textbf{ROE}} \\\\",
  "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}",
  "\\textbf{Model} & \\textbf{Intro} & \\textbf{MDF} & \\textbf{Tag} & \\textbf{No Tag} & \\textbf{Tag} & \\textbf{No Tag} & \\textbf{Tag} & \\textbf{No Tag} \\\\",
  "\\midrule",
  data_lines,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_path)

cat(sprintf("Wrote %s (%d models)\n", output_path, length(model_order)))
