#!/usr/bin/env python3
"""Generate the oracle-condition Stage 2 aggregate LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from table_utils import (
    TableDataError,
    lines_to_text,
    parse_float,
    parse_paths,
    read_delimited,
    write_text_atomic,
)

METRICS = ("Entry_F1", "MDF_Fields_F1", "ReadOrderEdit")
HIGHER_IS_BETTER = {
    "Entry_F1": True,
    "MDF_Fields_F1": True,
    "ReadOrderEdit": False,
}
MODEL_ORDER = ("qwen3vl235", "claudeopus47", "gpt55", "gemini31pro")
MODEL_DISPLAY = {
    "qwen3vl235": "Qwen3-VL-235B",
    "claudeopus47": "Claude Opus 4.7",
    "gpt55": "GPT-5.5",
    "gemini31pro": "Gemini 3.1 Pro",
}
MODEL_SECTION = {
    "qwen3vl235": "Vision Language Models",
    "claudeopus47": "General-purpose LLMs",
    "gpt55": "General-purpose LLMs",
    "gemini31pro": "General-purpose LLMs",
}


def _condition_order(intro: bool, toolbox: bool) -> int:
    return {(False, False): 1, (True, False): 2, (False, True): 3, (True, True): 4}[
        intro, toolbox
    ]


def _load_aggregate_rows(source: Path) -> list[dict[str, object]]:
    required = ("experiment", "language", *METRICS)
    raw_rows = read_delimited(source, required_columns=required)
    rows: list[dict[str, object]] = []
    seen: set[tuple[str, bool, bool]] = set()
    for row_number, row in enumerate(raw_rows, start=2):
        if row["language"] != "__aggregate__" or "goldcheat" in row["experiment"]:
            continue
        experiment = row["experiment"]
        marker = "_high_mdf_"
        if marker not in experiment:
            raise TableDataError(
                f"{source}: row {row_number}: invalid experiment {experiment!r}"
            )
        model_key, remainder = experiment.split(marker, 1)
        if model_key not in MODEL_DISPLAY:
            raise TableDataError(
                f"{source}: row {row_number}: unknown model {model_key!r}"
            )
        intro = remainder.startswith("intro_")
        toolbox = not remainder.endswith("_notoolbox")
        key = (model_key, intro, toolbox)
        if key in seen:
            raise TableDataError(f"{source}: duplicate aggregate condition {key!r}")
        seen.add(key)
        rows.append(
            {
                "model_key": model_key,
                "intro": intro,
                "toolbox": toolbox,
                **{
                    metric: parse_float(
                        row[metric], source=source, field=metric, row_number=row_number
                    )
                    for metric in METRICS
                },
            }
        )
    expected = {
        (model, intro, toolbox)
        for model in MODEL_ORDER
        for intro in (False, True)
        for toolbox in (False, True)
    }
    if seen != expected:
        missing = sorted(expected - seen)
        extra = sorted(seen - expected)
        raise TableDataError(
            f"{source}: incomplete Stage 2 aggregate conditions; missing={missing}, extra={extra}"
        )
    return sorted(
        rows,
        key=lambda row: (
            MODEL_ORDER.index(str(row["model_key"])),
            _condition_order(bool(row["intro"]), bool(row["toolbox"])),
        ),
    )


def render_table(repo_root: Path) -> str:
    """Render the oracle-condition Stage 2 summary."""
    source = (
        repo_root
        / "evaluations"
        / "stage2_mdf_lang_script_eval"
        / "stage2_mdf_eval_summary.csv"
    )
    rows = _load_aggregate_rows(source)
    displayed = {
        metric: [round(float(row[metric]), 2) for row in rows] for metric in METRICS
    }
    best = {
        metric: (max(values) if HIGHER_IS_BETTER[metric] else min(values))
        for metric, values in displayed.items()
    }

    def cell(metric: str, index: int) -> str:
        value = f"{float(rows[index][metric]):.2f}"
        return (
            rf"\textbf{{{value}}}"
            if displayed[metric][index] == best[metric]
            else value
        )

    lines = [
        "% Auto-generated by tables/scripts/stage2_summary_table.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{2pt}",
        r"\caption{Stage 2 MDF evaluation results aggregated by model. Check marks indicate that the corresponding condition was enabled.}",
        r"\label{tab:stage2-mdf-aggregate}",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        "\\textbf{Model} & \\textbf{Intro} & \\textbf{MDF} & \\textbf{Ent. F1} & \\textbf{MDF F1} & \\textbf{ROE} \\\\",
        r"\midrule",
    ]
    current_section: str | None = None
    for index, row in enumerate(rows):
        model_key = str(row["model_key"])
        section = MODEL_SECTION[model_key]
        if section != current_section:
            if current_section is not None:
                lines.append(r"\midrule")
            lines.append(
                rf"\multicolumn{{6}}{{l}}{{\cellcolor{{gray!10}}\textit{{{section}}}}} \\"
            )
            current_section = section
        intro = r"\cmark" if row["intro"] else ""
        toolbox = r"\cmark" if row["toolbox"] else ""
        lines.append(
            f"{MODEL_DISPLAY[model_key]} & {intro} & {toolbox} & "
            f"{cell('Entry_F1', index)} & {cell('MDF_Fields_F1', index)} & "
            f"{cell('ReadOrderEdit', index)} \\\\"
        )
    lines.extend((r"\bottomrule", r"\end{tabular}", r"\end{table}"))
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``stage2_summary.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "stage2_summary.tex"
    write_text_atomic(output_path, render_table(repo_root))
    print(f"Wrote {output_path} ({len(MODEL_ORDER)} models x 4 conditions)")


if __name__ == "__main__":
    main()
