#!/usr/bin/env Rscript
#
# Build the per-dictionary Stage 2 MDF evaluation LaTeX table (Entry Accuracy/MDF Fields F1/ReadOrderEdit for each dictionary individually) for the oracle condition.
#
# Usage:
#   Rscript evaluations/scripts/stage2_dictionary_table.R
#
# Output:
#   evaluations/tables/stage2_by_dictionary.tex

suppressWarnings(suppressMessages({
  script_path <- commandArgs(trailingOnly = FALSE)
  script_arg <- sub("^--file=", "", script_path[grep("^--file=", script_path)])
  repo_root <- if (length(script_arg)) normalizePath(file.path(dirname(script_arg), "..", "..")) else getwd()
}))

summary_csv <- file.path(repo_root, "evaluations", "stage2_mdf_lang_script_eval_stage1-gold", "stage2_mdf_eval_summary.csv")
output_dir <- file.path(repo_root, "tables", "tables")
output_path <- file.path(output_dir, "stage2_by_dictionary.tex")

if (!file.exists(summary_csv)) {
  stop(sprintf("Stage 2 summary CSV not found: %s", summary_csv))
}

results <- read.csv(summary_csv, stringsAsFactors = FALSE)
metric_cols <- c("Record_Accuracy", "MDF_Fields_F1", "ReadOrderEdit")
higher_is_better <- c(Record_Accuracy = TRUE, MDF_Fields_F1 = TRUE, ReadOrderEdit = FALSE)

results <- results[results$language != "__aggregate__" & !grepl("goldcheat", results$experiment), ]
if (nrow(results) == 0) {
  stop("No per-dictionary rows found (excluding _goldcheat experiments) in the summary CSV.")
}

# --- Parse "<model>_high_mdf_<intro|nointro>_<toolbox|notoolbox>" ---
results$model_key <- sub("_high_mdf_.*$", "", results$experiment)
remainder <- sub("^.*_high_mdf_", "", results$experiment)
results$intro_flag <- startsWith(remainder, "intro_")
results$toolbox_flag <- !endsWith(remainder, "_notoolbox")

model_display <- c(
  gemini31pro = "Gemini 3.1 Pro",
  gpt55 = "GPT-5.5",
  claudeopus47 = "Claude Opus 4.7",
  qwen3vl235 = "Qwen3-VL-235B"
)
model_order <- c("gemini31pro", "gpt55", "claudeopus47", "qwen3vl235")

unknown_models <- setdiff(results$model_key, names(model_display))
if (length(unknown_models)) {
  stop(sprintf("Unrecognized model key(s) in experiment names: %s", paste(unknown_models, collapse = ", ")))
}

# Row order within a dictionary's block: intro+OCR, intro only, OCR only, neither.
combo_order <- function(intro_flag, toolbox_flag) {
  ifelse( intro_flag &  toolbox_flag, 1,
  ifelse( intro_flag & !toolbox_flag, 2,
  ifelse(!intro_flag &  toolbox_flag, 3, 4)))
}
results$model_order <- match(results$model_key, model_order)
results$row_order <- combo_order(results$intro_flag, results$toolbox_flag)

fmt <- function(x) sprintf("%.3f", x)

build_dictionary_block <- function(dict_name) {
  block <- results[results$language == dict_name, ]
  block <- block[order(block$model_order, block$row_order), ]
  expected_rows <- length(model_order) * 4
  if (nrow(block) != expected_rows) {
    stop(sprintf(
      "%s: expected %d rows (4 models x 4 conditions), found %d.",
      dict_name, expected_rows, nrow(block)
    ))
  }
  block
}

all_dictionaries <- sort(unique(results$language))

# Best-score bolding is scoped per (dictionary, model) group of 4 rows,
# decided at display precision (3 d.p.) so exact ties (e.g. a model scoring
# a perfect 1.000 under every condition) all get bolded together.
mark_best <- function(block) {
  best_mask <- lapply(metric_cols, function(col) rep(FALSE, nrow(block)))
  names(best_mask) <- metric_cols
  for (model_key in unique(block$model_key)) {
    idx <- which(block$model_key == model_key)
    for (col in metric_cols) {
      rounded <- round(block[[col]][idx], 3)
      best <- if (higher_is_better[[col]]) max(rounded) else min(rounded)
      best_mask[[col]][idx[rounded == best]] <- TRUE
    }
  }
  best_mask
}

cell <- function(block, best_mask, col, i) {
  value <- fmt(block[[col]][i])
  if (isTRUE(best_mask[[col]][i])) sprintf("\\textbf{%s}", value) else value
}

row_block_lines <- function(dict_name) {
  block <- build_dictionary_block(dict_name)
  best_mask <- mark_best(block)
  lines <- vapply(seq_len(nrow(block)), function(i) {
    intro_mark <- if (isTRUE(block$intro_flag[i])) "\\cmark" else ""
    ocr_mark <- if (isTRUE(block$toolbox_flag[i])) "\\cmark" else ""
    sprintf(
      "%s & %s & %s & %s & %s & %s",
      model_display[[block$model_key[i]]], intro_mark, ocr_mark,
      cell(block, best_mask, "Record_Accuracy", i),
      cell(block, best_mask, "MDF_Fields_F1", i),
      cell(block, best_mask, "ReadOrderEdit", i)
    )
  }, character(1))
  lines
}

# --- Pair dictionaries two-per-row (alphabetical) ---
n_dicts <- length(all_dictionaries)
pairs <- split(all_dictionaries, ceiling(seq_len(n_dicts) / 2))

lines <- c(
  "% Auto-generated by evaluations/scripts/stage2_dictionary_table.R -- do not edit by hand.",
  "\\begin{table*}[!h]",
  "  \\centering",
  "  \\scriptsize",
  "  \\setlength{\\tabcolsep}{2.4pt}",
  "  \\renewcommand{\\arraystretch}{1.06}",
  "  \\begin{adjustbox}{max width=\\textwidth}",
  "  \\begin{tabular}{lccccc@{\\hspace{0.9em}}lccccc}",
  "  \\toprule",
  paste(
    "  \\textbf{Model} & \\textbf{Intro} & \\textbf{OCR} & \\textbf{Ent. Acc.} & \\textbf{Fields F1} & \\textbf{Order} &",
    "\\textbf{Model} & \\textbf{Intro} & \\textbf{OCR} & \\textbf{Ent. Acc.} & \\textbf{Fields F1} & \\textbf{Order} \\\\"
  ),
  "  \\midrule"
)

for (idx in seq_along(pairs)) {
  pair <- pairs[[idx]]
  left_lines <- row_block_lines(pair[1])
  right_lines <- if (length(pair) == 2) row_block_lines(pair[2]) else NULL

  if (is.null(right_lines)) {
    # Odd dictionary out: pad the right side with empty cells matching left length.
    right_lines <- rep("\\multicolumn{6}{l}{}", length(left_lines))
  }

  lines <- c(lines, sprintf(
    "  \\rowcolor{green!12}\\multicolumn{6}{l}{\\textit{%s}} & \\multicolumn{6}{l}{\\textit{%s}} \\\\",
    pair[1], if (length(pair) == 2) pair[2] else ""
  ))

  stopifnot(length(left_lines) == length(right_lines))
  for (i in seq_along(left_lines)) {
    lines <- c(lines, sprintf("  %s & %s \\\\", left_lines[i], right_lines[i]))
  }

  if (idx != length(pairs)) {
    lines <- c(lines, "  \\midrule")
  }
}

lines <- c(lines,
  "  \\bottomrule",
  "  \\end{tabular}",
  "  \\end{adjustbox}",
  "  \\caption{Stage 2 MDF evaluation results grouped by dictionary. Check marks indicate enabled inputs; blank cells indicate disabled inputs. Bold scores mark the best setting for each model within a dictionary (highest Entry Accuracy and MDF Fields F1; lowest ReadOrderEdit).}",
  "  \\label{tab:stage2-mdf-by-dictionary-modelwise-best}",
  "\\end{table*}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_path)

cat(sprintf("Wrote %s (%d dictionaries)\n", output_path, n_dicts))
