#!/usr/bin/env Rscript
#
# Build the Stage 1 evaluation summary LaTeX table (Table 1), aggregating scores across all dictionaries with vs. without the alphabet hint.
#
# Usage:
#   Rscript evaluations/scripts/stage1_summary_table.R
#
# Output:
#   evaluations/tables/stage1_summary.tex

suppressWarnings(suppressMessages({
  script_path <- commandArgs(trailingOnly = FALSE)
  script_arg <- sub("^--file=", "", script_path[grep("^--file=", script_path)])
  repo_root <- if (length(script_arg)) normalizePath(file.path(dirname(script_arg), "..", "..")) else getwd()
}))

summary_csv <- file.path(repo_root, "evaluations", "stage1_flat_per_lang_script_eval", "stage1_flat_eval_summary.csv")
output_dir <- file.path(repo_root, "tables", "tables")
output_path <- file.path(output_dir, "stage1_summary.tex")

if (!file.exists(summary_csv)) {
  stop(sprintf("Stage 1 summary CSV not found: %s", summary_csv))
}

results <- read.csv(summary_csv, stringsAsFactors = FALSE)

metric_cols <- c("TextEdit", "GCER", "WER", "typography_f1", "ReadOrderEdit")
missing_cols <- setdiff(c("experiment", metric_cols), names(results))
if (length(missing_cols)) {
  stop(sprintf("Missing expected column(s) in summary CSV: %s", paste(missing_cols, collapse = ", ")))
}

# --- Aggregate: macro-average per experiment across all dictionary rows ---
agg <- aggregate(
  results[, metric_cols],
  by = list(experiment = results$experiment),
  FUN = function(x) mean(as.numeric(x), na.rm = TRUE)
)
n_dict <- aggregate(
  list(n_dictionaries = results$experiment),
  by = list(experiment = results$experiment),
  FUN = length
)
agg <- merge(agg, n_dict, by = "experiment")

# --- Map experiment name -> (display model, alphabet flag, section, row order) ---
row_spec <- data.frame(
  experiment = c(
    "GLM-OCR-flat_noalpha", "GLM-OCR-flat_alpha",
    "Mathpix-OCR", "MinerU2.5-Pro", "PaddleOCR-VL-1.5",
    "qwen3vl235_flat_noalpha", "qwen3vl235_flat_alpha",
    "claudeopus47_flat_noalpha", "claudeopus47_flat_alpha",
    "gpt55_flat_noalpha", "gpt55_flat_alpha",
    "gemini3flash_flat_noalpha", "gemini3flash_flat_alpha",
    "gemini31pro_flat_noalpha", "gemini31pro_flat_alpha"
  ),
  model = c(
    "GLM-OCR", "GLM-OCR",
    "Mathpix", "MinerU2.5-Pro", "PaddleOCR-VL-1.5",
    "Qwen3-VL-235B", "Qwen3-VL-235B",
    "Claude Opus 4.7", "Claude Opus 4.7",
    "GPT-5.5", "GPT-5.5",
    "Gemini 3 Flash", "Gemini 3 Flash",
    "Gemini 3.1 Pro", "Gemini 3.1 Pro"
  ),
  alphabet = c(
    FALSE, TRUE,
    FALSE, FALSE, FALSE,
    FALSE, TRUE,
    FALSE, TRUE,
    FALSE, TRUE,
    FALSE, TRUE,
    FALSE, TRUE
  ),
  section = c(
    "OCR systems", "OCR systems",
    "OCR systems", "OCR systems", "OCR systems",
    "Vision Language Models", "Vision Language Models",
    "General-purpose LLMs", "General-purpose LLMs",
    "General-purpose LLMs", "General-purpose LLMs",
    "General-purpose LLMs", "General-purpose LLMs",
    "General-purpose LLMs", "General-purpose LLMs"
  ),
  row_order = seq_len(15),
  stringsAsFactors = FALSE
)

table_data <- merge(row_spec, agg, by = "experiment", all.x = TRUE)
table_data <- table_data[order(table_data$row_order), ]

unmapped_experiments <- setdiff(agg$experiment, row_spec$experiment)
if (length(unmapped_experiments)) {
  warning(sprintf(
    "Experiment(s) present in summary CSV but not in the Table 1 row map (skipped): %s",
    paste(unmapped_experiments, collapse = ", ")
  ))
}
if (any(is.na(table_data$TextEdit))) {
  missing_exp <- table_data$experiment[is.na(table_data$TextEdit)]
  stop(sprintf(
    "Row map references experiment(s) missing from summary CSV: %s",
    paste(missing_exp, collapse = ", ")
  ))
}

# --- Column display names + "lower is better" vs "higher is better" ---
display_cols <- c("TextEdit" = "Edit", "GCER" = "GCER", "WER" = "WER",
                   "typography_f1" = "Mrk. F1", "ReadOrderEdit" = "Order")
higher_is_better <- c(TextEdit = FALSE, GCER = FALSE, WER = FALSE,
                       typography_f1 = TRUE, ReadOrderEdit = FALSE)

fmt <- function(x) sprintf("%.2f", x)

# Best-score bolding: global winner(s) per column, decided on the full-precision
# values (not the 2 d.p. display rounding) so near-ties that only look equal
# after rounding don't both get bolded. Exact ties in the raw value are bolded
# together.
best_mask <- lapply(metric_cols, function(col) {
  raw <- table_data[[col]]
  best <- if (higher_is_better[[col]]) max(raw) else min(raw)
  raw == best
})
names(best_mask) <- metric_cols

cell <- function(col, i) {
  value <- fmt(table_data[[col]][i])
  if (isTRUE(best_mask[[col]][i])) sprintf("\\textbf{%s}", value) else value
}

# --- Emit LaTeX ---
lines <- character(0)
lines <- c(lines,
  "% Auto-generated by evaluations/scripts/stage1_summary_table.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\small",
  "\\setlength{\\tabcolsep}{1.6pt}",
  "\\renewcommand{\\arraystretch}{1.00}",
  "\\caption{Stage 1 OCR evaluation results aggregated across 30 dictionaries, comparing transcription with and without the source-language alphabet list in the prompt. Check marks indicate that the alphabet (A) was supplied. \\textit{Best aggregate scores are bolded: lower is better for Edit, GCER, WER, and Order; higher is better for Markup F1.}}",
  "\\label{tab:stage1-aggregate-alphabet}",
  "\\begin{adjustbox}{max width=\\textwidth}",
  "\\begin{tabular}{lcrrrrr}",
  "\\toprule",
  "\\textbf{Model} & \\textbf{A} & \\textbf{Edit} & \\textbf{GCER} & \\textbf{WER} & \\textbf{Mrk. F1} & \\textbf{Order} \\\\",
  "\\midrule"
)

sections_in_order <- unique(table_data$section)
for (sec in sections_in_order) {
  lines <- c(lines, sprintf("\\multicolumn{7}{l}{\\cellcolor{gray!10}\\textit{%s}} \\\\", sec))
  sec_rows <- which(table_data$section == sec)
  for (i in sec_rows) {
    checkmark <- if (isTRUE(table_data$alphabet[i])) "\\cmark" else ""
    lines <- c(lines, sprintf(
      "%s & %s & %s & %s & %s & %s & %s \\\\",
      table_data$model[i], checkmark,
      cell("TextEdit", i), cell("GCER", i), cell("WER", i),
      cell("typography_f1", i), cell("ReadOrderEdit", i)
    ))
  }
  lines <- c(lines, "\\midrule")
}
lines <- lines[-length(lines)]  # drop the trailing \midrule before \bottomrule

lines <- c(lines,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{adjustbox}",
  "\\end{table}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_path)

cat(sprintf("Wrote %s (%d rows, aggregated over %d dictionaries each)\n",
            output_path, nrow(table_data), unique(table_data$n_dictionaries)[1]))
