#!/usr/bin/env python3
"""Generate the Stage 2 per-dictionary MDF evaluation LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
import re

from table_utils import TableDataError, lines_to_text, parse_float, parse_paths, read_delimited, write_text_atomic

METRICS = ("Record_Accuracy", "MDF_Fields_F1", "ReadOrderEdit")
HIGHER_IS_BETTER = {"Record_Accuracy": True, "MDF_Fields_F1": True, "ReadOrderEdit": False}
MODEL_SPEC = (
    ("gemini31pro", "Gemini 3.1 Pro"),
    ("gpt55", "GPT-5.5"),
    ("claudeopus47", "Claude Opus 4.7"),
    ("qwen3vl235", "Qwen3-VL-235B"),
)
EXPERIMENT_PATTERN = re.compile(
    r"^(?P<model>[^_]+)_high_mdf_(?P<intro>intro|nointro)_(?P<toolbox>toolbox|notoolbox)$"
)
CONDITIONS = ((True, True), (True, False), (False, True), (False, False))


def _render_block(dictionary: str, rows: list[dict[str, object]], source: Path) -> list[str]:
    keyed: dict[tuple[str, bool, bool], dict[str, float]] = {}
    for row in rows:
        key = (str(row["model"]), bool(row["intro"]), bool(row["toolbox"]))
        if key in keyed:
            raise TableDataError(f"{source}: duplicate Stage 2 condition for {dictionary}: {key}")
        keyed[key] = {metric: float(row[metric]) for metric in METRICS}
    expected = {(model, intro, toolbox) for model, _ in MODEL_SPEC for intro, toolbox in CONDITIONS}
    if set(keyed) != expected:
        raise TableDataError(
            f"{source}: {dictionary} condition set mismatch; missing={sorted(expected - set(keyed))}, "
            f"extra={sorted(set(keyed) - expected)}"
        )

    lines: list[str] = []
    for model, display in MODEL_SPEC:
        model_rows = [keyed[(model, intro, toolbox)] for intro, toolbox in CONDITIONS]
        rounded_best = {
            metric: (
                max(round(row[metric], 3) for row in model_rows)
                if HIGHER_IS_BETTER[metric]
                else min(round(row[metric], 3) for row in model_rows)
            )
            for metric in METRICS
        }
        for intro, toolbox in CONDITIONS:
            values = keyed[(model, intro, toolbox)]
            cells: list[str] = []
            for metric in METRICS:
                rendered = f"{values[metric]:.3f}"
                cells.append(
                    rf"\textbf{{{rendered}}}"
                    if round(values[metric], 3) == rounded_best[metric]
                    else rendered
                )
            intro_mark = r"\cmark" if intro else ""
            toolbox_mark = r"\cmark" if toolbox else ""
            lines.append(f"{display} & {intro_mark} & {toolbox_mark} & {' & '.join(cells)}")
    return lines


def render_table(repo_root: Path) -> str:
    """Render the Stage 2 dictionary-level table."""
    source = repo_root / "evaluations" / "stage2_mdf_lang_script_eval_stage1-gold" / "stage2_mdf_eval_summary.csv"
    raw_rows = read_delimited(source, required_columns=("experiment", "language", *METRICS))
    grouped: dict[str, list[dict[str, object]]] = {}
    known_models = {model for model, _ in MODEL_SPEC}
    for row_number, row in enumerate(raw_rows, start=2):
        if row["language"] == "__aggregate__" or "goldcheat" in row["experiment"]:
            continue
        match = EXPERIMENT_PATTERN.fullmatch(row["experiment"])
        if match is None:
            raise TableDataError(f"{source}: row {row_number}: invalid experiment {row['experiment']!r}")
        model = match.group("model")
        if model not in known_models:
            raise TableDataError(f"{source}: row {row_number}: unknown model {model!r}")
        grouped.setdefault(row["language"], []).append(
            {
                "model": model,
                "intro": match.group("intro") == "intro",
                "toolbox": match.group("toolbox") == "toolbox",
                **{
                    metric: parse_float(row[metric], source=source, field=metric, row_number=row_number)
                    for metric in METRICS
                },
            }
        )
    if not grouped:
        raise TableDataError(f"{source}: no non-goldcheat per-dictionary rows")
    dictionaries = sorted(grouped)
    blocks = {dictionary: _render_block(dictionary, grouped[dictionary], source) for dictionary in dictionaries}
    lines = [
        "% Auto-generated by tables/scripts/stage2_dictionary_table.py -- do not edit by hand.",
        r"\begin{table*}[!h]",
        r"  \centering",
        r"  \scriptsize",
        r"  \setlength{\tabcolsep}{2.4pt}",
        r"  \renewcommand{\arraystretch}{1.06}",
        r"  \begin{adjustbox}{max width=\textwidth}",
        r"  \begin{tabular}{lccccc@{\hspace{0.9em}}lccccc}",
        r"  \toprule",
        r"  \textbf{Model} & \textbf{Intro} & \textbf{OCR} & \textbf{Ent. Acc.} & \textbf{Fields F1} & \textbf{Order} & \textbf{Model} & \textbf{Intro} & \textbf{OCR} & \textbf{Ent. Acc.} & \textbf{Fields F1} & \textbf{Order} \\",
        r"  \midrule",
    ]
    pairs = [dictionaries[index : index + 2] for index in range(0, len(dictionaries), 2)]
    for pair_index, pair in enumerate(pairs):
        left = blocks[pair[0]]
        right = blocks[pair[1]] if len(pair) == 2 else [r"\multicolumn{6}{l}{}"] * len(left)
        right_name = pair[1] if len(pair) == 2 else ""
        lines.append(
            rf"  \rowcolor{{green!12}}\multicolumn{{6}}{{l}}{{\textit{{{pair[0]}}}}} & \multicolumn{{6}}{{l}}{{\textit{{{right_name}}}}} \\"
        )
        if len(left) != len(right):
            raise TableDataError(f"paired dictionary blocks differ in length: {pair}")
        lines.extend(f"  {left_line} & {right_line} \\\\" for left_line, right_line in zip(left, right, strict=True))
        if pair_index != len(pairs) - 1:
            lines.append(r"  \midrule")
    lines.extend(
        (
            r"  \bottomrule",
            r"  \end{tabular}",
            r"  \end{adjustbox}",
            r"  \caption{Stage 2 MDF evaluation results grouped by dictionary. Check marks indicate enabled inputs; blank cells indicate disabled inputs. Bold scores mark the best setting for each model within a dictionary (highest Entry Accuracy and MDF Fields F1; lowest ReadOrderEdit).}",
            r"  \label{tab:stage2-mdf-by-dictionary-modelwise-best}",
            r"\end{table*}",
        )
    )
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``stage2_by_dictionary.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "stage2_by_dictionary.tex"
    write_text_atomic(output_path, render_table(repo_root))
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
