#!/usr/bin/env python3
"""Generate the Stage 1 per-dictionary evaluation LaTeX table."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from table_utils import TableDataError, lines_to_text, parse_float, parse_paths, read_delimited, write_text_atomic

METRICS = ("TextEdit", "GCER", "WER", "typography_f1", "ReadOrderEdit")
HIGHER_IS_BETTER = {metric: metric == "typography_f1" for metric in METRICS}
ROW_SPEC = (
    ("GLM-OCR-flat_noalpha", "GLM-OCR", False, "OCR systems"),
    ("GLM-OCR-flat_alpha", "GLM-OCR", True, "OCR systems"),
    ("Mathpix-OCR", "Mathpix", False, "OCR systems"),
    ("MinerU2.5-Pro", "MinerU2.5-Pro", False, "OCR systems"),
    ("PaddleOCR-VL-1.5", "PaddleOCR-VL-1.5", False, "OCR systems"),
    ("qwen3vl235_flat_noalpha", "Qwen3-VL-235B", False, "Vision Language Models"),
    ("qwen3vl235_flat_alpha", "Qwen3-VL-235B", True, "Vision Language Models"),
    ("claudeopus47_flat_noalpha", "Claude Opus 4.7", False, "General-purpose LLMs"),
    ("claudeopus47_flat_alpha", "Claude Opus 4.7", True, "General-purpose LLMs"),
    ("gpt55_flat_noalpha", "GPT-5.5", False, "General-purpose LLMs"),
    ("gpt55_flat_alpha", "GPT-5.5", True, "General-purpose LLMs"),
    ("gemini3flash_flat_noalpha", "Gemini 3 Flash", False, "General-purpose LLMs"),
    ("gemini3flash_flat_alpha", "Gemini 3 Flash", True, "General-purpose LLMs"),
    ("gemini31pro_flat_noalpha", "Gemini 3.1 Pro", False, "General-purpose LLMs"),
    ("gemini31pro_flat_alpha", "Gemini 3.1 Pro", True, "General-purpose LLMs"),
)


def _render_block(
    dictionary: str,
    values: dict[str, dict[str, float]],
) -> list[str]:
    best = {
        metric: (
            max(row[metric] for row in values.values())
            if HIGHER_IS_BETTER[metric]
            else min(row[metric] for row in values.values())
        )
        for metric in METRICS
    }

    def cell(experiment: str, metric: str) -> str:
        raw = values[experiment][metric]
        rendered = f"{raw:.2f}"
        return rf"\textbf{{{rendered}}}" if raw == best[metric] else rendered

    display_dictionary = dictionary.replace("Kurdish_Turkish", "Kurdish-Turkish")
    lines = [rf"\multicolumn{{7}}{{>{{\columncolor{{green!12}}}}l}}{{\textbf{{{display_dictionary}}}}}"]
    current_section: str | None = None
    for experiment, model, alphabet, section in ROW_SPEC:
        if section != current_section:
            lines.append(rf"\multicolumn{{7}}{{>{{\columncolor{{gray!12}}}}l}}{{\emph{{{section}}}}}")
            current_section = section
        mark = r"\cmark" if alphabet else ""
        lines.append(
            f"{model} & {mark} & {cell(experiment, 'TextEdit')} & {cell(experiment, 'GCER')} & "
            f"{cell(experiment, 'WER')} & {cell(experiment, 'typography_f1')} & "
            f"{cell(experiment, 'ReadOrderEdit')}"
        )
    return lines


def render_table(repo_root: Path) -> str:
    """Render the per-dictionary Stage 1 table."""
    source = repo_root / "evaluations" / "stage1_flat_per_lang_script_eval" / "stage1_flat_eval_summary.csv"
    raw_rows = read_delimited(source, required_columns=("experiment", "language", *METRICS))
    expected_experiments = {row[0] for row in ROW_SPEC}
    experiments = {row["experiment"] for row in raw_rows}
    if experiments != expected_experiments:
        raise TableDataError(
            f"{source}: experiment set mismatch; missing={sorted(expected_experiments - experiments)}, "
            f"extra={sorted(experiments - expected_experiments)}"
        )

    grouped: dict[str, dict[str, dict[str, float]]] = {}
    for row_number, row in enumerate(raw_rows, start=2):
        dictionary_rows = grouped.setdefault(row["language"], {})
        experiment = row["experiment"]
        if experiment in dictionary_rows:
            raise TableDataError(f"{source}: duplicate ({row['language']}, {experiment}) row")
        dictionary_rows[experiment] = {
            metric: parse_float(row[metric], source=source, field=metric, row_number=row_number)
            for metric in METRICS
        }
    if len(grouped) != 30:
        raise TableDataError(f"{source}: found {len(grouped)} dictionaries, expected 30")
    for dictionary, values in grouped.items():
        if set(values) != expected_experiments:
            raise TableDataError(f"{source}: incomplete experiment set for {dictionary}")

    dictionaries = sorted(grouped)
    blocks = {dictionary: _render_block(dictionary, grouped[dictionary]) for dictionary in dictionaries}
    lines = [
        "% Auto-generated by tables/scripts/stage1_dictionary_table.py -- do not edit by hand.",
        r"\begin{table*}[!hp]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.2pt}",
        r"\renewcommand{\arraystretch}{1.08}",
        r"\begin{adjustbox}{max width=\textwidth}",
        r"\begin{tabular}{lcrrrrr@{\qquad}lcrrrrr}",
        r"\toprule",
        r"\textbf{Model} & \textbf{Alph.} & \textbf{Edit} & \textbf{GCER} & \textbf{WER} & \textbf{Mrk. F1} & \textbf{RO} & \textbf{Model} & \textbf{Alph.} & \textbf{Edit} & \textbf{GCER} & \textbf{WER} & \textbf{Mrk. F1} & \textbf{RO} \\",
        r"\midrule",
        "",
    ]
    pairs = [dictionaries[index : index + 2] for index in range(0, len(dictionaries), 2)]
    for pair_index, pair in enumerate(pairs):
        left = blocks[pair[0]]
        right = blocks[pair[1]] if len(pair) == 2 else [r"\multicolumn{7}{l}{}"] * len(left)
        if len(left) != len(right):
            raise TableDataError(f"paired dictionary blocks differ in length: {pair}")
        lines.extend(f"{left_line} & {right_line} \\\\" for left_line, right_line in zip(left, right, strict=True))
        if pair_index != len(pairs) - 1:
            lines.extend((r"\addlinespace[0.35em]", r"\midrule", r"\addlinespace[0.35em]", ""))
    lines.extend(
        (
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{adjustbox}",
            r"\caption{Stage 1 dictionary-specific evaluation results grouped by dictionary.}",
            r"\end{table*}",
        )
    )
    return lines_to_text(lines)


def main(argv: Sequence[str] | None = None) -> None:
    """Generate ``stage1_by_dictionary.tex``."""
    repo_root, output_dir = parse_paths(__file__, __doc__ or "", argv)
    output_path = output_dir / "stage1_by_dictionary.tex"
    write_text_atomic(output_path, render_table(repo_root))
    print(f"Wrote {output_path} (30 dictionaries, 30 rows total)")


if __name__ == "__main__":
    main()
