#!/usr/bin/env Rscript
#
# Build the Stage 2 MDF evaluation summary LaTeX table for the end-to-end condition (Stage 2 fed Stage 1's own predicted text, not gold).
#
# Usage:
#   Rscript evaluations/scripts/stage2_e2e_summary_table.R
#
# Output:
#   evaluations/tables/stage2_e2e_summary.tex

suppressWarnings(suppressMessages({
  script_path <- commandArgs(trailingOnly = FALSE)
  script_arg <- sub("^--file=", "", script_path[grep("^--file=", script_path)])
  repo_root <- if (length(script_arg)) normalizePath(file.path(dirname(script_arg), "..", "..")) else getwd()
}))

summary_csv <- file.path(repo_root, "evaluations", "stage2_mdf_lang_script_eval", "stage2_mdf_eval_summary.csv")
output_dir <- file.path(repo_root, "tables", "tables")
output_path <- file.path(output_dir, "stage2_e2e_summary.tex")

if (!file.exists(summary_csv)) {
  stop(sprintf("Stage 2 e2e summary CSV not found: %s", summary_csv))
}

results <- read.csv(summary_csv, stringsAsFactors = FALSE)
metric_cols <- c("Record_Accuracy", "MDF_Fields_F1", "ReadOrderEdit")
higher_is_better <- c(Record_Accuracy = TRUE, MDF_Fields_F1 = TRUE, ReadOrderEdit = FALSE)

agg <- results[results$language == "__aggregate__" & !grepl("goldcheat", results$experiment), ]
if (nrow(agg) == 0) {
  stop("No '__aggregate__' rows found (excluding _goldcheat experiments) in the summary CSV.")
}

# --- Parse "<model>_high_mdf_<intro|nointro>_<toolbox|notoolbox>_from_<stage1-experiment>" ---
agg$model_key <- sub("_high_mdf_.*$", "", agg$experiment)
remainder <- sub("^.*_high_mdf_", "", agg$experiment)
condition_part <- sub("_from_.*$", "", remainder)
agg$intro_flag <- startsWith(condition_part, "intro_")
agg$toolbox_flag <- !endsWith(condition_part, "_notoolbox")

model_display <- c(
  qwen3vl235 = "Qwen3-VL-235B",
  claudeopus47 = "Claude Opus 4.7",
  gpt55 = "GPT-5.5",
  gemini31pro = "Gemini 3.1 Pro"
)
model_section <- c(
  qwen3vl235 = "Vision Language Models",
  claudeopus47 = "General-purpose LLMs",
  gpt55 = "General-purpose LLMs",
  gemini31pro = "General-purpose LLMs"
)

unknown_models <- setdiff(agg$model_key, names(model_display))
if (length(unknown_models)) {
  stop(sprintf("Unrecognized model key(s) in experiment names: %s", paste(unknown_models, collapse = ", ")))
}

model_order <- c("qwen3vl235", "claudeopus47", "gpt55", "gemini31pro")
combo_order <- function(intro_flag, toolbox_flag) {
  # nointro/notoolbox, intro/notoolbox, nointro/toolbox, intro/toolbox
  ifelse(!intro_flag & !toolbox_flag, 1,
  ifelse( intro_flag & !toolbox_flag, 2,
  ifelse(!intro_flag &  toolbox_flag, 3, 4)))
}
agg$model_order <- match(agg$model_key, model_order)
agg$row_order <- combo_order(agg$intro_flag, agg$toolbox_flag)
agg <- agg[order(agg$model_order, agg$row_order), ]

expected_rows <- length(model_order) * 4
if (nrow(agg) != expected_rows) {
  stop(sprintf("Expected %d rows (4 models x 4 conditions), found %d -- check for missing/duplicate experiments.",
               expected_rows, nrow(agg)))
}

fmt <- function(x) sprintf("%.2f", x)

# Best-score bolding is GLOBAL across the whole table (not per model/section),
# decided at DISPLAY precision (2 d.p.) so exact ties (e.g. several rows
# rounding to the same best value) all get bolded together -- same convention
# as stage2_summary_table.R.
best_mask <- lapply(metric_cols, function(col) {
  rounded <- round(agg[[col]], 2)
  best <- if (higher_is_better[[col]]) max(rounded) else min(rounded)
  rounded == best
})
names(best_mask) <- metric_cols

cell <- function(col, i) {
  value <- fmt(agg[[col]][i])
  if (isTRUE(best_mask[[col]][i])) sprintf("\\textbf{%s}", value) else value
}

lines <- c(
  "% Auto-generated by evaluations/scripts/stage2_e2e_summary_table.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\small",
  "\\setlength{\\tabcolsep}{2pt}",
  "\\caption{Stage 2 MDF evaluation results aggregated by model, end-to-end condition (Stage 2 fed Stage 1's own predicted text). Check marks indicate that the corresponding condition was enabled.}",
  "\\label{tab:stage2-mdf-aggregate-e2e}",
  "\\begin{tabular}{lccccc}",
  "\\toprule",
  "\\textbf{Model} & \\textbf{Intro} & \\textbf{MDF} & \\textbf{Ent. Acc.} & \\textbf{MDF F1} & \\textbf{ROE} \\\\",
  "\\midrule"
)

current_section <- NULL
for (i in seq_len(nrow(agg))) {
  section <- model_section[[agg$model_key[i]]]
  if (!identical(section, current_section)) {
    if (!is.null(current_section)) lines <- c(lines, "\\midrule")
    lines <- c(lines, sprintf("\\multicolumn{6}{l}{\\cellcolor{gray!10}\\textit{%s}} \\\\", section))
    current_section <- section
  }
  intro_mark <- if (isTRUE(agg$intro_flag[i])) "\\cmark" else ""
  toolbox_mark <- if (isTRUE(agg$toolbox_flag[i])) "\\cmark" else ""
  lines <- c(lines, sprintf(
    "%s & %s & %s & %s & %s & %s \\\\",
    model_display[[agg$model_key[i]]], intro_mark, toolbox_mark,
    cell("Record_Accuracy", i), cell("MDF_Fields_F1", i), cell("ReadOrderEdit", i)
  ))
}

lines <- c(lines,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}"
)

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
writeLines(lines, output_path)

cat(sprintf("Wrote %s (%d models x 4 conditions)\n", output_path, length(model_order)))
